### ISSUE TITLE
Any long term plans for this project?

### ISSUE THREAD

**Issue by xackery** [brihernandez/FreelancerFlightExample#2]
I love this stuff. I'm messing with a project if you'd love to collab on it, feel free to reply to this issue. Looking to rally a team and make a foundation based similarly on Freelancer, particularly the dog fighting UI and mechanics that you captured here.

**Comment by PokerfaceCactus** [comment]
@xackery if he doesn't i'd love to work along on something like this. tho i only have self taught experience in unity so i don't know how usefull i'd be. i love the idea of making a spiritual successor to freelancer tho.

**Comment by xackery** [comment]
@brandonvdongen  https://discord.gg/9RGsZ6p feel free to join our discord and chat more
